# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8d2e37a8bf882863adfb89dd40ffe2e903209d95744287ea1fbca459f910f4817a950816f7cd8e8ff760bf1fe61ab5efbc300147526772c03bd91d27ba2e13

test:
  secret_key_base: 64f9d5e0964dc00cc82b4864ae63ab68834d75b7bc60be015e427daefd47199bc32725d2b98fbaf3871acf1c043866115bfefb19dcb04e29a2e4cf7b738d5ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
